language: minimal

os:
  - osx
  - linux

before_install:
  - export PATH=$HOME/.deno/bin:$PATH

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh

script:
  - deno version
  - mkdir tmp
  - deno run --allow-run --allow-env test/test-task.ts --cwd=test | tee tmp/result
  - deno run --allow-run --allow-env test/test.ts
  - deno run --allow-run --allow-env example/example.ts --cwd=example all
