install:
  - ps: iex (iwr https://deno.land/x/install/install.ps1)

test_script:
  - deno -v
  - mkdir tmp
  - deno --allow-run --allow-write test/test-task.ts --cwd=test test | tee tmp/result
  - deno test/test.ts --allow-run
  - deno example/example.ts --cwd=example all --allow-run

build: off
